-- =========================================================
-- NutriBlend — Supabase Database Schema
-- File: supabase/schema.sql
-- =========================================================

create extension if not exists "pgcrypto";

-- =========================================================
-- Helpers & Role Functions
-- =========================================================

-- Helper function to check if user is admin
create or replace function public.is_admin(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
    and role = 'admin'
  );
$$;

-- Helper function to check if user is delivery partner
create or replace function public.is_delivery_partner(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role = 'delivery_partner'
  );
$$;

-- =========================================================
-- 1. PROFILES
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  phone text,
  address text,
  role text not null default 'customer',
  fitness_goal text,
  fitness_level text,
  age integer,
  gender text,
  weight numeric,
  height numeric,
  workout_type text,
  dietary_preference text,
  allergies text[] default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_email_idx on public.profiles(email);

-- =========================================================
-- 2. PRODUCTS
-- =========================================================
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  protein text,
  price numeric not null default 0,
  category text,
  description text,
  image text,
  ingredients jsonb default '[]'::jsonb,
  benefits jsonb default '[]'::jsonb,
  calories text,
  quantity text,
  stock_status text not null default 'In Stock',
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category);
create index if not exists products_active_idx on public.products(is_active);
create index if not exists products_stock_status_idx on public.products(stock_status);

-- =========================================================
-- 3. PLANS
-- =========================================================
create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price numeric not null default 0,
  duration text,
  protein text,
  category text default 'Plans',
  description text,
  image text,
  includes jsonb default '[]'::jsonb,
  features jsonb default '[]'::jsonb,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists plans_active_idx on public.plans(is_active);

-- =========================================================
-- 4. ADDRESSES
-- =========================================================
create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  phone text not null,
  street text not null,
  landmark text,
  city text not null,
  state text not null,
  pincode text not null,
  type text not null default 'Home',
  is_default boolean not null default false,
  full_name text,
  address_line_1 text,
  address_line_2 text,
  district text,
  country text default 'India',
  postal_code text,
  latitude numeric,
  longitude numeric,
  address_type text default 'Home',
  delivery_time text default 'Morning',
  custom_delivery_time text,
  order_note text,
  alternate_phone text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists addresses_user_id_idx on public.addresses(user_id);
create index if not exists addresses_user_default_idx on public.addresses(user_id, is_default);

-- =========================================================
-- 5. ORDERS
-- =========================================================
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  product_name text,
  price integer,
  created_at timestamp without time zone default now(),
  user_id uuid references auth.users(id) on delete set null,
  email text,
  qty integer default 1,
  total numeric default 0,
  subtotal numeric default 0,
  delivery_fee numeric default 0,
  delivery_option text,
  delivery_status text default 'Pending',
  delivery_partner_name text,
  delivery_partner_phone text,
  estimated_delivery_time text,
  kitchen_lat numeric,
  kitchen_lng numeric,
  customer_lat numeric,
  customer_lng numeric,
  delivery_lat numeric,
  delivery_lng numeric,
  payment_status text default 'Pending',
  payment_method text default 'COD',
  upi_id text,
  status text default 'Placed',
  address jsonb,
  items jsonb default '[]'::jsonb,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  cancel_reason text,
  cancelled_at timestamp without time zone,
  delivery_partner_id uuid references auth.users(id) on delete set null
);

create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_delivery_status_idx on public.orders(delivery_status);
create index if not exists orders_payment_method_idx on public.orders(payment_method);
create index if not exists orders_razorpay_order_id_idx on public.orders(razorpay_order_id);
create index if not exists orders_delivery_partner_id_idx on public.orders(delivery_partner_id);

-- =========================================================
-- 6. MONTHLY SUBSCRIPTIONS
-- =========================================================
create table if not exists public.monthly_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id uuid references public.plans(id) on delete set null,
  plan_name text,
  plan_price numeric default 0,
  plan_duration text,
  plan_protein text,
  status text not null default 'active',
  start_date timestamptz not null default now(),
  end_date timestamptz,
  order_id bigint references public.orders(id) on delete set null,
  cancelled_at timestamptz,
  cancel_reason text,
  created_at timestamptz not null default now()
);

create index if not exists monthly_subscriptions_user_id_idx on public.monthly_subscriptions(user_id);
create index if not exists monthly_subscriptions_status_idx on public.monthly_subscriptions(status);

-- =========================================================
-- 7. GYM PARTNER INQUIRIES
-- =========================================================
create table if not exists public.gym_partner_inquiries (
  id uuid primary key default gen_random_uuid(),
  gym_name text not null,
  owner_name text not null,
  phone text not null,
  city text not null,
  expected_daily_orders integer,
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists gym_inquiries_status_idx on public.gym_partner_inquiries(status);
create index if not exists gym_inquiries_created_at_idx on public.gym_partner_inquiries(created_at desc);

-- =========================================================
-- 8. CONTACT INQUIRIES
-- =========================================================
create table if not exists public.contact_inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists contact_inquiries_created_at_idx on public.contact_inquiries(created_at desc);

-- =========================================================
-- 9. NOTIFICATIONS
-- =========================================================
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  notification_type text not null default 'general',
  is_read boolean not null default false,
  order_id bigint references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_id_idx on public.notifications(user_id);
create index if not exists notifications_unread_idx on public.notifications(user_id, is_read);
create index if not exists notifications_created_idx on public.notifications(created_at desc);

-- =========================================================
-- 10. DELIVERY TRACKING
-- =========================================================
create table if not exists public.delivery_tracking (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  delivery_partner_id uuid references auth.users(id) on delete set null,
  latitude numeric,
  longitude numeric,
  status text default 'assigned',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists delivery_tracking_order_id_idx on public.delivery_tracking(order_id);
create index if not exists delivery_tracking_partner_id_idx on public.delivery_tracking(delivery_partner_id);
create index if not exists delivery_tracking_updated_idx on public.delivery_tracking(updated_at desc);

-- =========================================================
-- 11. RAZORPAY WEBHOOK EVENTS
-- =========================================================
create table if not exists public.razorpay_webhook_events (
  id bigint generated by default as identity primary key,
  event text,
  payload jsonb,
  razorpay_signature text,
  processing_status text not null default 'received',
  created_at timestamptz not null default now()
);

create index if not exists razorpay_webhook_events_event_idx on public.razorpay_webhook_events(event);
create index if not exists razorpay_webhook_events_created_at_idx on public.razorpay_webhook_events(created_at desc);

-- =========================================================
-- 12. AUDIT LOGS
-- =========================================================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  table_name text not null,
  record_id text,
  old_values jsonb,
  new_values jsonb,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_user_id_idx on public.audit_logs(user_id);
create index if not exists audit_logs_table_idx on public.audit_logs(table_name);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);

-- =========================================================
-- DB Triggers & Trigger Functions
-- =========================================================

-- Trigger function: Update timestamp of delivery tracking location
create or replace function public.update_delivery_tracking_timestamp()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists delivery_tracking_updated_at on public.delivery_tracking;
create trigger delivery_tracking_updated_at
  before update on public.delivery_tracking
  for each row execute function public.update_delivery_tracking_timestamp();

-- Trigger function: Notify user on order status change
create or replace function public.notify_on_order_status_change()
returns trigger language plpgsql security definer as $$
declare
  v_title   text;
  v_message text;
  v_type    text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  case new.status
    when 'Placed' then
      v_title   := 'Order Placed!';
      v_message := 'Your NutriBlend order has been placed successfully.';
      v_type    := 'order_placed';
    when 'Preparing' then
      v_title   := 'Order Being Prepared';
      v_message := 'Your order is now being freshly prepared for you.';
      v_type    := 'order_preparing';
    when 'Ready for Pickup' then
      v_title   := 'Order Ready!';
      v_message := 'Your order is ready and will be dispatched shortly.';
      v_type    := 'order_ready';
    when 'Out for Delivery' then
      v_title   := 'Out for Delivery!';
      v_message := 'Your order is on the way. Track it live from your orders.';
      v_type    := 'out_for_delivery';
    when 'Delivered' then
      v_title   := 'Order Delivered!';
      v_message := 'Your NutriBlend order has been delivered. Enjoy!';
      v_type    := 'delivered';
    when 'Cancelled' then
      v_title   := 'Order Cancelled';
      v_message := 'Your order has been cancelled. Contact us if needed.';
      v_type    := 'order_cancelled';
    else
      return new;
  end case;

  if new.user_id is not null then
    insert into public.notifications (user_id, title, message, notification_type, order_id)
    values (new.user_id, v_title, v_message, v_type, new.id);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_order_status_notification on public.orders;
create trigger trg_order_status_notification
  after update of status on public.orders
  for each row execute function public.notify_on_order_status_change();

-- Trigger function: Notify user on payment confirmed
create or replace function public.notify_on_payment_confirmed()
returns trigger language plpgsql security definer as $$
begin
  if new.payment_status is not distinct from old.payment_status then
    return new;
  end if;

  if new.payment_status = 'Paid' and new.user_id is not null then
    insert into public.notifications (user_id, title, message, notification_type, order_id)
    values (
      new.user_id,
      'Payment Confirmed!',
      'Your payment was successful and your order is being processed.',
      'payment_success',
      new.id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_payment_notification on public.orders;
create trigger trg_payment_notification
  after update of payment_status on public.orders
  for each row execute function public.notify_on_payment_confirmed();

-- Trigger function: Notify user on new order insertion
create or replace function public.notify_on_new_order()
returns trigger language plpgsql security definer as $$
begin
  if new.user_id is not null then
    insert into public.notifications (user_id, title, message, notification_type, order_id)
    values (
      new.user_id,
      'Order Received!',
      'Thank you for ordering from NutriBlend. Your order is being confirmed.',
      'order_placed',
      new.id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_new_order_notification on public.orders;
create trigger trg_new_order_notification
  after insert on public.orders
  for each row execute function public.notify_on_new_order();
