-- Optional Razorpay webhook event log table.
-- Run this in Supabase SQL Editor if you want webhook debugging history.

create table if not exists public.razorpay_webhook_events (
  id bigint generated by default as identity primary key,
  event text,
  payload jsonb,
  razorpay_signature text,
  processing_status text not null default 'received',
  created_at timestamptz not null default now()
);

alter table public.razorpay_webhook_events enable row level security;

drop policy if exists "Admins can view webhook events" on public.razorpay_webhook_events;
create policy "Admins can view webhook events"
on public.razorpay_webhook_events
for select
to authenticated
using (public.is_admin(auth.uid()));

-- Inserts happen from backend service role key, so no public insert policy is needed.
create index if not exists razorpay_webhook_events_event_idx
on public.razorpay_webhook_events(event);

create index if not exists razorpay_webhook_events_created_at_idx
on public.razorpay_webhook_events(created_at desc);
